(#247) Name param in event tracking to handle both http and https
NCIOCPL/glossary-app pull request #262
Opened 2022-10-07 19:15 UTC by belaolsonNIH

- name parameter in event tracking now handles both http and https protocols 
Closes #247

2022-10-11 05:19 UTC, seyilonge-nci approved these changes

2022-11-01 14:12 UTC, sarinapadilla approved these changes
`react-app-dev` works, so this passes for me!

2022-11-01 20:33 UTC, KateMashkinaNIH requested changes

2022-11-01 20:33 UTC, KateMashkinaNIH commented on src/views/Terms/TermList.jsx
> +				canonicalHost.replace(/https:\/\/|http:\/\//, '') +
there is one more place to update it : GlossaryApp:Load:ExpandResults event

2022-11-08 16:06 UTC, KateMashkinaNIH approved these changes

2022-11-08 17:19 UTC, arcepaul approved these changes

2022-11-08 17:19 UTC, merged